### ISSUE TITLE
Gallery viewer has trouble with more than 2 images

### ISSUE THREAD

**Issue by Koekoek19** [Nihlus/digos-ambassador#35]
Whenever viewing a gallery of a character with more than 2 images the buttons dont work as expected
When pressing the "next image" command, the buttons reset, which the bot interprets as another action, skipping the second image and moving on to the third.

**Comment by Koekoek19** [comment]
After some further testing, this also goes for the in-server `!ch list` viewer if the pages exceed 2.

The !help viewer in dms works as intended/expected

**Comment by Nihlus** [comment]
Weird. I'll investigate some more. Can you expand a little on the exact sequence of actions that causes this to happen?

**Comment by Koekoek19** [comment]
Not really sure how much more exact i can be about it.

Whenever a viewer is used in a server (say Lucy's Gallery viewer) or a list with more than two pages, it gets kinda buggy with flipping through the pages. Usually it skips a page when selecting next or previous, sometimes it doesnt.

**Comment by Nihlus** [comment]
Fixed in 47c03c7.
