### ISSUE TITLE
[AUTOMATED] Too long descriptions break !ch show

### ISSUE THREAD

**Issue by Koekoek19** [Nihlus/digos-ambassador#36]
Please attach the generated report to this issue!

**Describe the bug**
Exceeding a certain limit in descriptions causes the "!ch show" command

**To Reproduce**
1. Add a long description to a character with `!ch set description`
2. !ch show character

**Expected behavior**
A small frame should pop up with the description summary and name of the character, this now doesnt work. 

[bug-report Desc-view.zip](https://github.com/Nihlus/digos-ambassador/files/3187451/bug-report.Desc-view.zip)

**Comment by Nihlus** [comment]
Fixed in 5fa783e by restricting character description lengths to at most 1000 characters.
