### ISSUE TITLE
Character roles do not get applied properly

### ISSUE THREAD

**Issue by Koekoek19** [Nihlus/digos-ambassador#38]
Swapping between different characters causes the roles assigned to them to not be assigned properly. They are still listed correctly in the character cards. 

They can be added by using the `!ch set role` command, but as soon as one swaps characters it breaks again.

Side note: the same role can be applied to a character multiple times without error message popping up stating the character already has the role. Not sure if it relates to this, but figured i'd mention it

**Comment by Nihlus** [comment]
Fixed in d6202d4 and its preceding commits. The main big issue was how Discord.NET handles (or more accurately, doesn't handle) database context scoping, and its unbelievably shitty async internals.
