### ISSUE TITLE
!contact @user does not trigger a response

### ISSUE THREAD

**Issue by Koekoek19** [Nihlus/digos-ambassador#78]
Please attach the generated report to this issue!

**Describe the bug**
When using the `!contact user` no response occurs on the user's end
`!contact` works fine

**To Reproduce**
1. Run `!contact Username` 

**Expected behavior**
It is expected the bot contacts the listed user, but nothing of the sort happens. There is also no report generated, nor a message in server to make clear something has happened.

**Comment by Nihlus** [comment]
This variant of the command requires you to be able to mention everyone. I'll make that more clear.
