### ISSUE TITLE
!roleplay server set default-user-role @Bass-test-role

### ISSUE THREAD

**Issue by BassWithers** [Nihlus/digos-ambassador#79]
**Describe the bug**
When trying to run the command above, literally nothing happens

**To Reproduce**
1. Go to Bass's Channel
2. Run command '!roleplay server set default-user-role @Bass-test-role'
3. With parameters '!roleplay server'

**Expected behavior**
i expect it to give me a response

**Comment by Nihlus** [comment]
Command was run while the bot was down; closing as invalid.
