### ISSUE TITLE
[AUTOMATED] <!ch Create "Rpname here" problems>

### ISSUE THREAD

**Issue by BassWithers** [Nihlus/digos-ambassador#81]
Please attach the generated report to this issue!

**Describe the bug**
When i type in [!ch create "BagleSeeds"] The bot sent me a bug report. When observing the category it is made under the channel is created, however, the channel is then deleted (which is when i was sent the bug)

**To Reproduce**
1. Go to #Roleplay-plugin 
2. Run command !ch create "BagleSeeds"
3. With parameters !ch create

**Expected behavior**
I expect a channel to be created 

[Bug_Report 03_07_2020 (Roleplay Plugin).zip](https://github.com/Nihlus/digos-ambassador/files/4871290/Bug_Report.03_07_2020.Roleplay.Plugin.zip)

**Comment by Nihlus** [comment]
The error message displayed to the user has been improved. This is a permission issue with the roleplaying category; the bot needs a default override for itself. This should probably be improved as well, but that's another issue.
