### ISSUE TITLE
[AUTOMATED] !kink update-db

### ISSUE THREAD

**Issue by BassWithers** [Nihlus/digos-ambassador#82]
**Describe the bug**
When trying to use the !kink update-db Command nothing happens. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Bot DMs
2. Run the command !kink update-db
3. With parameters !kink update-db

**Expected behaviour**
I expect it to update the kink database

**Comment by Nihlus** [comment]
This is intended behaviour; only the owner of the bot instance can update the kink database.
