### ISSUE TITLE
Deleting bans does not work

### ISSUE THREAD

**Issue by Koekoek19** [Nihlus/digos-ambassador#84]
https://discordapp.com/channels/@me/544527560848179210/729332545497464892

**Describe the bug**
Deleting a ban through the bot does not work and gives out an error report

**To Reproduce**
1. use `!ban JohnDoe "reason"`
2. Run `!ban delete ID`

**Expected behavior**
The ban gets removed and the person can rejoin the server at will.

**Comment by Nihlus** [comment]
Fixed.
