### ISSUE TITLE
Suggestions related to !ban

### ISSUE THREAD

**Issue by Koekoek19** [Nihlus/digos-ambassador#85]
Currently the `!ban list` command is kind of redundant, as it is tied to the user specifically, and when the user has no bans, it shows no bans, and when the user is banned, you cant @ that specific user anymore to look why they have been banned.

Rather, the suggestion is to make `!ban list` a global list, so it displays users, reason for ban and duration, rather than per user.

Unsure how feasible this is, but make use of it as you will.

**Comment by Nihlus** [comment]
Fixed.
