### ISSUE TITLE
[AUTOMATED] !rp join

### ISSUE THREAD

**Issue by BassWithers** [Nihlus/digos-ambassador#86]
**Describe the bug**
When trying to join an RP i am sent a bug report and i do not join the RP 

**To Reproduce**
1. Go to Roleplay Plugin
2. Run command !rp join bagle
3. With parameters !rp join

**Expected behavior**to join the RP
[BugReportRoleplayPlugin.zip](https://github.com/Nihlus/digos-ambassador/files/4875346/BugReportRoleplayPlugin.zip)

**Comment by Nihlus** [comment]
Fixed in eb97f95.
