### ISSUE TITLE
Server join message can not be removed.

### ISSUE THREAD

**Issue by Azazial** [Nihlus/digos-ambassador#87]
Context: Core Plugin

Providing `!server set join-message` with no argument results in the bot complaining via PM about a lack of no argument.

Attempting `!server set join-message ""` results in the bot complaining the join message must not be empty.  The method of reply is inconsistent on the same command.

The lack of ability to set a null join message is inconsistent with the initial state of the join message before setting one (i.e. "No join message set").

Suggest `!server set join-message ""` remove the join message.

**Comment by Nihlus** [comment]
Fixed. `!server clear-join-message` can now be used to remove a set join message.
