### ISSUE TITLE
!ch set default reports error

### ISSUE THREAD

**Issue by mittsmittsmitts** [Nihlus/digos-ambassador#88]
Please attach the generated report to this issue!

**Describe the bug**
!ch set default reports that a users characters are not owned by them

**To Reproduce**
1. Go to #character-stuff
2. Run command '!ch create Arabella'
3. Run command '!ch set default Arabella'

**Expected behavior**
Expect the character to be set as the default character for the user

**Comment by Nihlus** [comment]
Fixed in eb97f95.
