### ISSUE TITLE
!server show command is too terse and ambiguous

### ISSUE THREAD

**Issue by Azazial** [Nihlus/digos-ambassador#89]
Context: Core Plugin
Command: `!server show`

The command `!server show` returns highly ambiguous results relating to the First-join Message setting.
The states appear to be
`Yes`
`No` (which does not seem to be able to be returned to)
`No (join message set)`

The third of these results is too terse which makes it easily misinterpreted.
It can easily be read as "No join message is set" rather than the intended "No join message will be sent, but a join message is set".
Being terse here is not an advantage.

Suggestion:
`!server show` always displays the contents of the first join message if one is set.

Then you have
`Display First-join Message
<Yes or No>
First-join Message
<"Unset" or $FirstJoinMessage>`

Some other phrasing such as "message displayed upon first join" could further set the results apart for easier interpretation.

**Comment by Nihlus** [comment]
Fixed.
