### ISSUE TITLE
!user info throws "too many parameters" when given a uuid it can't process.

### ISSUE THREAD

**Issue by Azazial** [Nihlus/digos-ambassador#90]
Providing the `!user info` command with an invalid discord ID or a discord ID for a user which is not in the same server as the bot results in the bot PMing "The input text has too many parameters."

The number of parameters, one, is correct.

Example cases
`!user info 107625160936271872` Kyr's ID
`!user info 1337` invalid ID

**Comment by Nihlus** [comment]
This is an issue in the underlying Discord library. Unfortunately, it's not something I can fix.
