### ISSUE TITLE
Autoroles with affirmation required continuously post the request for confirmation

### ISSUE THREAD

**Issue by Koekoek19** [Nihlus/digos-ambassador#91]
Please attach the generated report to this issue!

**Describe the bug**
When having an autorole with affirmation required, the reminder of needing affirmation gets posted over and over again, until the conditions for the role are no longer met, or the person gets affirmed

**To Reproduce**
1. Set up an autorole which requires affirmation
2. Add a condition to the autorole and enable it
3. Once the condition is met, the bot continuously posts the need for affirmation

**Expected behavior**
A single message where a user needs affirmation should be posted in the notification channel.
Tested with both a reaction based condition and a time based condition

**Screenshots**

**Comment by Nihlus** [comment]
Fixed.
